import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

import { auth } from "../server/auth";
import { getFeatureFlags } from "../server/feature-flags";
import { FeatureFlagsProvider } from "../shared/feature-flags/context";

import { AuthSessionProvider } from "./providers/session-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const featureFlags = getFeatureFlags();
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthSessionProvider session={session}>
          <FeatureFlagsProvider flags={featureFlags}>{children}</FeatureFlagsProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
